export const products = [
    {
        id: 'product-01',
        slug: 'product-01',
        title: 'Daybed',
        xsImage: '/images/products-commerce/daybed.jpeg',
        smImage: '/images/products-commerce/daybed.jpeg',
        mdImage: '/images/products-commerce/daybed.jpeg',
        altImage: 'Product Image',
        price: 7999,
        desc: 'Daybed available in white , grey , black , blue , beige.',
        sku: 500,
        category: 'lounge furniture',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture',
        isFeatured: false,
    },
    {
        id: 'product-02',
        slug: 'product-02',
        title: 'Chest of drawers',
        xsImage: '/images/products-commerce/chest-of-drawers.jpeg',
        smImage: '/images/products-commerce/chest-of-drawers.jpeg',
        mdImage: '/images/products-commerce/chest-of-drawers.jpeg',
        altImage: 'Product Image',
        price: 9500,
        desc: '',
        sku: 500,
        category: 'bedroom furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'bedroom furniture ',
        isFeatured: false,
    },
    {
        id: 'product-03',
        slug: 'product-03',
        title: 'Table set',
        xsImage: '/images/products-commerce/table-set.jpeg',
        smImage: '/images/products-commerce/table-set.jpeg',
        mdImage: '/images/products-commerce/table-set.jpeg',
        altImage: 'Product Image',
        price: 42000,
        desc: `10 seater - R42000
        8 seater - R37000
        6 seater - R29500`,
        sku: 500,
        category: 'dining furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'dining furniture ',
        isFeatured: false,
    },
    {
        id: 'product-04',
        slug: 'product-04',
        title: 'Couch',
        xsImage: '/images/products-commerce/couch-01.jpeg',
        smImage: '/images/products-commerce/couch-01.jpeg',
        mdImage: '/images/products-commerce/couch-01.jpeg',
        altImage: 'Product Image',
        price: 11999,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-05',
        slug: 'product-05',
        title: 'Couch',
        xsImage: '/images/products-commerce/couch-02.jpeg',
        smImage: '/images/products-commerce/couch-02.jpeg',
        mdImage: '/images/products-commerce/couch-02.jpeg',
        altImage: 'Product Image',
        price: 10999,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-06',
        slug: 'product-06',
        title: 'Occasional chair',
        xsImage: '/images/products-commerce/occasional-chair-01.jpeg',
        smImage: '/images/products-commerce/occasional-chair-01.jpeg',
        mdImage: '/images/products-commerce/occasional-chair-01.jpeg',
        altImage: 'Product Image',
        price: 6500,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-07',
        slug: 'product-07',
        title: 'Couch set',
        xsImage: '/images/products-commerce/couch-set.jpeg',
        smImage: '/images/products-commerce/couch-set.jpeg',
        mdImage: '/images/products-commerce/couch-set.jpeg',
        altImage: 'Product Image',
        price: 39999,
        desc: 'L shape and occasional chair',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-08',
        slug: 'product-08',
        title: 'Occasional chair',
        xsImage: '/images/products-commerce/occasional-chair-02.jpeg',
        smImage: '/images/products-commerce/occasional-chair-02.jpeg',
        mdImage: '/images/products-commerce/occasional-chair-02.jpeg',
        altImage: 'Product Image',
        price: 9999,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-09',
        slug: 'product-09',
        title: 'Tv stand',
        xsImage: '/images/products-commerce/tv-stand.jpeg',
        smImage: '/images/products-commerce/tv-stand.jpeg',
        mdImage: '/images/products-commerce/tv-stand.jpeg',
        altImage: 'Product Image',
        price: 6500,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-10',
        slug: 'product-10',
        title: 'Headboard base + ottoman',
        xsImage: '/images/products-commerce/headboard-ottoman.jpeg',
        smImage: '/images/products-commerce/headboard-ottoman.jpeg',
        mdImage: '/images/products-commerce/headboard-ottoman.jpeg',
        altImage: 'Product Image',
        price: 28000,
        desc: `King R28,000
        Queen R26,000
        Double R24,000`,
        category: 'bedroom furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'bedroom furniture ',
        isFeatured: false,
    },
    {
        id: 'product-11',
        slug: 'product-11',
        title: 'Headboard + base',
        xsImage: '/images/products-commerce/headboard-base.jpeg',
        smImage: '/images/products-commerce/headboard-base.jpeg',
        mdImage: '/images/products-commerce/headboard-base.jpeg',
        altImage: 'Product Image',
        price: 14900,
        desc: `King R14900
        Queen R13,000
        Double R11999`,
        category: 'bedroom furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'bedroom furniture ',
        isFeatured: false,
    },
    {
        id: 'product-12',
        slug: 'product-12',
        title: 'headboard and base',
        xsImage: '/images/products-commerce/headboard-base-02.jpeg',
        smImage: '/images/products-commerce/headboard-base-02.jpeg',
        mdImage: '/images/products-commerce/headboard-base-02.jpeg',
        altImage: 'Product Image',
        price: 15500,
        desc: `King R15500
        Queen R13999
        Double R11999`,
        category: 'bedroom furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'bedroom furniture ',
        isFeatured: false,
    },
    {
        id: 'product-13',
        slug: 'product-13',
        title: 'L shape couch',
        xsImage: '/images/products-commerce/l-shape-couch-01.jpeg',
        smImage: '/images/products-commerce/l-shape-couch-01.jpeg',
        mdImage: '/images/products-commerce/l-shape-couch-01.jpeg',
        altImage: 'Product Image',
        price: 16500,
        desc: '2.8 by 1.8 ',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-14',
        slug: 'product-14',
        title: 'Tv stand',
        xsImage: '/images/products-commerce/tv-stand-01.jpeg',
        smImage: '/images/products-commerce/tv-stand-01.jpeg',
        mdImage: '/images/products-commerce/tv-stand-01.jpeg',
        altImage: 'Product Image',
        price: 16999,
        desc: 'On less than a 2.8 m wall space',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-15',
        slug: 'product-15',
        title: 'U shape couch',
        xsImage: '/images/products-commerce/u-shape-couch.jpeg',
        smImage: '/images/products-commerce/u-shape-couch.jpeg',
        mdImage: '/images/products-commerce/u-shape-couch.jpeg',
        altImage: 'Product Image',
        price: 25000,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-16',
        slug: 'product-16',
        title: 'L shape in euro leather ',
        xsImage: '/images/products-commerce/l-shape-couch-euro.jpeg',
        smImage: '/images/products-commerce/l-shape-couch-euro.jpeg',
        mdImage: '/images/products-commerce/l-shape-couch-euro.jpeg',
        altImage: 'Product Image',
        price: 17500,
        desc: '2.6 by 1.8',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-17',
        slug: 'product-17',
        title: '3,2,1 genuine leather set',
        xsImage: '/images/products-commerce/genuine-leather-set.jpeg',
        smImage: '/images/products-commerce/genuine-leather-set.jpeg',
        mdImage: '/images/products-commerce/genuine-leather-set.jpeg',
        altImage: 'Product Image',
        price: 69000,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-18',
        slug: 'product-18',
        title: 'Bar stools',
        xsImage: '/images/products-commerce/bar-stools.jpeg',
        smImage: '/images/products-commerce/bar-stools.jpeg',
        mdImage: '/images/products-commerce/bar-stools.jpeg',
        altImage: 'Product Image',
        price: 3999,
        desc: '',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-19',
        slug: 'product-19',
        title: 'TV Stand',
        xsImage: '/images/products-commerce/tv-stand-03.jpeg',
        smImage: '/images/products-commerce/tv-stand-03.jpeg',
        mdImage: '/images/products-commerce/tv-stand-03.jpeg',
        altImage: 'Product Image',
        price: 13400,
        desc: '2.8m',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
    {
        id: 'product-20',
        slug: 'product-20',
        title: 'L Shape',
        xsImage: '/images/products-commerce/l-shape.jpeg',
        smImage: '/images/products-commerce/l-shape.jpeg',
        mdImage: '/images/products-commerce/l-shape.jpeg',
        altImage: 'Product Image',
        price: 19500,
        desc: '3 meters by 1.8',
        category: 'lounge furniture ',
        availability: 'in-stock',
        size: 'large',
        color: 'white',
        tag: 'lounge furniture ',
        isFeatured: false,
    },
]